name: GeorgTorch
channels:
  - anaconda
  - conda-forge
  - prometeia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20200225.2
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - aliyun-python-sdk-core=2.13.19
  - aliyun-python-sdk-core-v3=2.13.11
  - aliyun-python-sdk-kms=2.10.1
  - anyio=2.2.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - arrow-cpp=0.17.1
  - async-timeout=3.0.1
  - async_generator=1.10
  - atpublic=1.0
  - attrs=20.3.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.175
  - azure-common=1.1.24
  - azure-nspkg=3.0.2
  - azure-storage-blob=2.1.0
  - azure-storage-common=2.1.0
  - babel=2.9.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.19.0
  - boost-cpp=1.72.0
  - boto3=1.17.41
  - botocore=1.20.41
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - configobj=5.0.6
  - coverage=5.5
  - crcmod=1.7
  - cryptography=3.4.7
  - cudatoolkit=11.0.221
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.22
  - cytoolz=0.11.0
  - dask-core=2021.3.1
  - decorator=4.4.2
  - defusedxml=0.7.1
  - distro=1.5.0
  - docutils=0.16
  - dpath=1.4.2
  - dvc=1.0.2
  - entrypoints=0.3
  - expat=2.3.0
  - flatten_json=0.1.6
  - flufl.lock=3.2
  - freetype=2.10.4
  - funcy=1.14
  - future=0.18.2
  - gflags=2.2.2
  - giflib=5.1.4
  - git=2.23.0
  - gitdb=4.0.7
  - gitdb2=4.0.2
  - gitpython=3.1.14
  - glog=0.4.0
  - gmp=6.2.1
  - google-api-core=1.25.1
  - google-api-python-client=1.9.1
  - google-auth=1.28.0
  - google-auth-httplib2=0.0.3
  - google-auth-oauthlib=0.4.4
  - google-cloud-core=1.6.0
  - google-cloud-storage=1.19.0
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - grandalf=0.6
  - grpc-cpp=1.30.0
  - grpcio=1.36.1
  - httplib2=0.18.1
  - icu=64.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonpath-ng=1.5.1
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20210216
  - libevent=2.1.8
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libwebp=1.0.1
  - libzopfli=1.0.3
  - lz4-c=1.9.2
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - nanotime=0.5.2
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.3
  - ninja=1.10.2
  - notebook=6.3.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauth2client=4.1.3
  - oauthlib=3.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - oss2=2.12.1
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pathspec=0.7.0
  - pcre=8.44
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - plotly=4.14.3
  - ply=3.11
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - protobuf=3.12.3
  - ptyprocess=0.7.0
  - pyarrow=0.17.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pycryptodome=3.10.1
  - pydot=1.2.4
  - pydrive2=1.4.14
  - pygments=2.8.1
  - pygtrie=2.3.2
  - pyjwt=1.7.1
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - re2=2020.06.01
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rsa=4.7.2
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - s3transfer=0.3.6
  - scikit-image=0.17.2
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - shortuuid=1.0.1
  - shtab=1.0.2
  - simplejson=3.17.2
  - six=1.15.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.35.3
  - tabulate=0.8.9
  - tensorboard-plugin-wit=1.6.0
  - tensorboardx=2.1
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift-compiler=0.13.0
  - thrift-cpp=0.13.0
  - tifffile=2021.3.17
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - uritemplate=3.0.1
  - urllib3=1.26.4
  - voluptuous=0.11.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zc.lockfile=2.0
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - filelock=
    - gdown=
    - opencv-python=
    - pip=
    - pycocotools=
    - seaborn=
    - tensorboard=
    - thop=
    - torch=
    - torchvision=

